# Generated by Django 3.2.11 on 2022-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
