# Generated by Django 3.2.11 on 2022-03-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220306_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='uuid',
        ),
    ]
