# Generated by Django 3.2.11 on 2022-03-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_id_profile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid',
            new_name='id',
        ),
    ]
