# Generated by Django 3.2.11 on 2022-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220306_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
