# Generated by Django 3.2.11 on 2022-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7fa35074ad30>', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
