# Generated by Django 3.2.11 on 2022-03-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_id_project_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uuid',
            new_name='id',
        ),
    ]
